/* For Tailwind config */
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './component/**/*.{js,vue,ts}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
    './plugins/**/*.{js,ts}',
    './app.vue',
    './error.vue',
  ],
    theme: {
      extend: {
        colors: {
          background: '#111111',
          surface: '#1a1a1a',
          accent: '#4A9EFF',
          muted: '#888888',
        },
        fontFamily: {
          // "<Family> fallback" entries are metric-matched local-font faces
          // generated by @nuxtjs/fontaine (size-adjust/ascent-override/
          // descent-override) so the fallback occupies the exact same box
          // as the real webfont — this is what prevents text from visibly
          // reflowing/shifting once the real webfonts finish loading and swap in.
          'sans': ['Space Grotesk', 'Space Grotesk fallback', 'Inter', 'Inter fallback', 'Helvetica Neue', 'Arial', 'sans-serif'],
          'display': ['Space Grotesk', 'Space Grotesk fallback', 'Montserrat', 'Montserrat fallback', 'Gotham', 'sans-serif'],
          'heading': ['Space Grotesk', 'Space Grotesk fallback', 'Poppins', 'sans-serif'],
          'space': ['Space Grotesk', 'Space Grotesk fallback', 'Helvetica Neue', 'Arial', 'sans-serif'],
        },
        fontWeight: {
          'normal': '400',
          'medium': '500',
          'semibold': '600',
          'bold': '700',
          'extrabold': '800'
        },
        boxShadow: {
          'glow': '0 0 40px rgba(74, 158, 255, 0.35)',
          'glow-sm': '0 0 20px rgba(74, 158, 255, 0.25)',
        },
        keyframes: {
          'spin-left': {
            from: { transform: 'rotate(0deg)' },
            to: { transform: 'rotate(-360deg)' },
          },
        },
        animation: {
          'spin-left': 'spin-left 0.6s linear infinite',
        },
      }
    }
  }